### PR TITLE
Better Preference Dialog

### PR DESCRIPTION
**Pull request by voldyman**
the new preferences dialog uses Gtk.Stack and modern widgets provided by Gtk to look awesome

### CODE REVIEW

**Comment by voldyman** [comment]
@emersion this might be of interest to you

**Comment by emersion** [comment]
screenshot from 2015-03-08 10 30 21

Switches are very large on GNOME Shell (don't know how they look in elementary).

**Comment by voldyman** [comment]
Yeah something isn't right, I also could not find a suitable way to display options where there are three possible results.
Like style sheet, default, custom, off. Of custom then select one

**Comment by emersion** [comment]
Also, there is no way to close the window in GNOME (see screenshot). You have to press `Esc`, but this isn't user-friendly.

**Comment by emersion** [comment]
If we don't manage to hide the file selection button for stylesheet, we can disable it.

**Comment by emersion** [comment]
:+1:

**Pull request merged**
