### PR TITLE
Updates discount to v2.1.7

### PR DESCRIPTION
**Pull request by emersion**
And adds fenced code blocks support :-)

### CODE REVIEW

**Comment by voldyman** [comment]
doesn't work for me, the generated html is not displayed on the preview web view.

**Comment by voldyman** [comment]
turns out the problem was that my internet is pretty slow and the web view download the stylesheet for every render, we need to figure out a better way.

**Comment by emersion** [comment]
Yes, I was thinking about this issue yesterday. I will include an offline default stylesheet.

Note that this is not related to this update.

**Comment by voldyman** [comment]
thanks for the pull request but i updated the master to use discount 2.1.8 and fixed the webkit issue i was talking about earlier.

**Pull request closed without merging**
