### PR TITLE
Adds POT and PO files for fr

### PR DESCRIPTION
**Pull request by emersion**
Sorry about commits including previous ones, I forgot to checkout master before creating new branches :-S

### CODE REVIEW

**Comment by emersion** [comment]
It's now working properly. :-)

**Comment by voldyman** [comment]
how do i test the french translation ?

**Comment by emersion** [comment]
You can run this command : `LANG=fr_FR.UTF-8 ./mark-my-words` ;-)

**Comment by voldyman** [comment]
hmm, doesn't work for me
```
┌─[voldyman@ares:~/code/em/build on feat-l10n!?]
└─> LANG=fr_FR.UTF-8 ./mark-my-words

(mark-my-words:10706): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.

(process:10712): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.
```

**Comment by emersion** [comment]
Yes, you'll have to install the French language pack on your system... Sorry about that

**Pull request merged**
